In [1]:
import pandas as pd
import numpy as np

In [2]:
data_arCarm= pd.read_csv("AR_car_preprocessing.csv", encoding="cp949")

In [5]:
data=data_arCarm.loc[:,['code','coname','house','analyst','carm','yy','mm','dd','title']]
data.tail(100)

,code,coname,house,analyst,carm,yy,mm,dd,title
39933,A030000,제일기획,흥국증권,이현정,-0.033407,2010,1,1,제일기획-안정적인 이익성장으로 차별화 기대
39934,A000810,삼성화재,HMC투자증권,박윤영,-0.003827,2011,12,12,삼성화재-10월 Review: 최고의 안정성에 이익모멘텀 추가
39935,A012750,에스원,KB투자증권,이지연,-0.005468,2011,11,11,에스원-안정성에 더해진 실적 개선 기대감
39936,A009540,한국조선해양,LIG투자증권,최광식,0.025687,2011,1,1,현대중공업-2011 어닝 모멘텀과 영업 기대감 최고
39937,A001630,종근당홀딩스,NH농협증권,고성진,0.084784,2011,8,8,종근당-2Q Review: 영업이익 기대 이상..하반기 실적호조 이어질 전망
...,...,...,...,...,...,...,...,...,...
40028,A097230,한진중공업,삼성증권,한영수,-0.039737,2014,2,2,한진중공업-이익개선 기대감 vs 이익전망을 변경시킬 수 있는 요소들
40029,A055550,신한지주,KB투자증권,유승창,-0.003910,2015,10,10,신한지주-이익 안정성 및 배당수익률 상승 기대감 유효
40030,A033660,아주캐피탈,삼성증권,김재우,0.013043,2016,11,11,아주캐피탈-3Q review-이익 안정성 매력적이나 중장기적 시장 입지 강화 필요
40031,A000120,CJ대한통운,키움증권,조병희,-0.016607,2018,1,1,"CJ대한통운-낮아진 기대감, 이익 증가 확인 이후 반등 기대"
40032,A000120,CJ대한통운,HMC투자증권,김정은,-0.040710,2011,3,3,"대한통운-안정적 이익 성장세 + M&A 프리미엄, 운송업종 최선호주 추천"

## 중복값 제거 (2가지 방법)

In [6]:
# 1) hard coding 방법 
title_list = list(set(data['title']))  # set은 허용 X
# print(title_list)
new_data= pd.DataFrame()

for i in title_list:
    tmp = data[data['title'] == i]
    if len(tmp) <= 1:
        new_data = pd.concat([new_data, tmp])

In [7]:
new_data

,code,coname,house,analyst,carm,yy,mm,dd,title
19102,A185750,종근당,SK증권,하태기,-0.066665,2015,10,10,종근당-임상 불확실성 반영한 현재 주가는 저평가권
9694,A000270,기아차,이트레이드증권,이명훈,-0.013239,2011,7,7,"기아차-2Q11 Preview: 견고한 실적 예상, 4분기 주목"
37805,A034220,LG디스플레이,한국투자증권,유종우,-0.042994,2017,1,1,LG디스플레이-좋은 실적과 함께 OLED로의 성공적인 전환이 필요한 때
2154,A011780,금호석유,키움증권,박중선,-0.004597,2015,5,5,금호석유-합성고무 수요 부진으로 실적 회복 더뎌
32171,A064420,케이피케미칼,신한금융투자,임지수,-0.014202,2010,5,5,케이피케미칼-2분기 글로벌 자회사의 지분법 이익 Jump
...,...,...,...,...,...,...,...,...,...
15598,A000100,유한양행,KDB대우증권,김현태,-0.002495,2014,3,3,유한양행-도입신약과 원료의약품이 실적 개선 견인
36744,A092200,디아이씨,신영증권,이재일,-0.010737,2016,11,11,"디아이씨-3분기 실적 혼조,하지만 긍정적 요소의 장기 영향력이 우세"
28076,A075180,새론오토모티브,하나금융투자,송선재,-0.036185,2017,3,3,새론오토모티브-중국 법인의 근본적인 성장 제고 방안이 필요
14823,A000830,삼성물산,토러스투자증권,박용희,-0.007227,2013,2,2,삼성물산-4Q12 NDR 후기: 2013년은 동사의 잠재력이 폭발하는 원년
25708,A006280,녹십자,HMC투자증권,강양구,-0.000437,2017,2,2,녹십자-4Q16 Review:모든 사업부 성장 중

In [8]:
print(new_data.shape)
removeDuplication_arCarm=new_data
# removeDuplication_arCarm.to_csv('./removeDuplication_arCarm.csv',encoding='cp949')/

(31714, 9)

In [26]:
# 2) drop_duplicates() 함수 사용 
# data.drop_duplicates(['title'], keep = False) 
# print(data.shape)

(40033, 9)

# toy

In [18]:
df = pd.DataFrame({"뉴스" :["오늘 날씨는 맑음입니다.","오늘 미세먼지는 나쁨입니다.","오늘 날씨는 맑음입니다."],
                 "인덱스":[1,2,3]})
df

df.drop_duplicates(['뉴스'], keep = 'first')

                뉴스  인덱스
0    오늘 날씨는 맑음입니다.    1
1  오늘 미세먼지는 나쁨입니다.    2

## title 안의 기업명 제거

In [9]:
# 기업명 
company=list(set(removeDuplication_arCarm['coname']))# uniqe한 기업명

In [10]:
# 기업명 제거 함수 정의 
def cleansing(title):
    if title.find("-") != -1: # 기업명이 존재한다면 # 해당단어가 존재하지 않으면, text.find(i) = -1 
        ind = title.index("-")
        rm = title[:ind+1]
        title = title.replace(rm,"").strip()
    return title

# 기업명 제거 
removeDuplication_arCarm['title']=removeDuplication_arCarm['title'].apply(lambda x: cleansing(x))

removeDuplication_arCarm['title'].head(20)

19102               임상 불확실성 반영한 현재 주가는 저평가권
9694        2Q11 Preview: 견고한 실적 예상, 4분기 주목
37805       좋은 실적과 함께 OLED로의 성공적인 전환이 필요한 때
2154                  합성고무 수요 부진으로 실적 회복 더뎌
32171              2분기 글로벌 자회사의 지분법 이익 Jump
13305                   조금은 밋밋함, 그러나 변화는 있다
32948                  계열편입 후 1년, 이제는 이익 성장
30300                         드릴십특화 대형 조선업체
19107                              보릿고개를 넘다
27888               빛을 발하는 IP사업, 2017년을 이끈다
31128                    PNG 사업, 장기투자 매력 부각
2814                 물류부문 실적 우려 해소, 고성장세 재개
3433     DPS는 720원이 아니라 800원, 저금리 시대의 투자 대안
16067                       이시기에 이만한 회사도 없다
14518                      건설중장비시장은 여전히 빙하기
38845         4분기 매출과 영업실적 호조, 지분법 손익은 기대이하
9480                     3분기 필름부문 수익성 감소 전망
32540           탐방노트: ‘12년 기대를 갖게하는 몇가지 요인들
15128                         多품종 多국가 진출 전략
17798                '13년 4분기 실적: 방향성에 투자하자
Name: title, dtype: object

In [11]:
ARCarm=removeDuplication_arCarm

## title 전처리

In [12]:
# title 전처리 
# 한글과 공백을 제하고 모두 제거 
ARCarm['title']=ARCarm['title'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")

# 데이터 정제후 빈문자열(na 로 바꾼 후) 제거 
ARCarm['title'].replace('',np.nan,inplace=True)
# print(text.isnull().sum())

# na 제거
ARCarm = ARCarm.dropna(subset=['title'])
# print(len(ARCarm))
# print(ARCarm.isnull().sum())

C:\Users\Public\Documents\ESTsoft\CreatorTemp/ipykernel_12032/1604558095.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  ARCarm['title']=ARCarm['title'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")

In [13]:
!pip install konlpy

Requirement already satisfied: konlpy in c:\users\stat510\anaconda3\lib\site-packages (0.6.0)
Requirement already satisfied: JPype1>=0.7.0 in c:\users\stat510\anaconda3\lib\site-packages (from konlpy) (1.3.0)
Requirement already satisfied: numpy>=1.6 in c:\users\stat510\anaconda3\lib\site-packages (from konlpy) (1.19.5)
Requirement already satisfied: lxml>=4.1.0 in c:\users\stat510\anaconda3\lib\site-packages (from konlpy) (4.6.3)

### (1) pos + okt 
- 출처: https://mkjjo.github.io/python/2019/07/09/korean_preprocessing.html

In [ ]:
from konlpy.tag import Okt
okt = Okt() # Okt(Open Korea Text)

ARCarm['nouns_pos']=ARCarm['title'].apply(okt.pos) # 형태소 토큰화 , 튜플 반환

In [18]:
ARCarm

,code,coname,house,analyst,carm,yy,mm,dd,title,nouns_pos
19102,A185750,종근당,SK증권,하태기,-0.066665,2015,10,10,임상 불확실성 반영한 현재 주가는 저평가권,"[(임, Noun), (상, Suffix), (불확실, Noun), (성, Suff..."
9694,A000270,기아차,이트레이드증권,이명훈,-0.013239,2011,7,7,견고한 실적 예상 분기 주목,"[(견고한, Adjective), (실적, Noun), (예상, Noun), (분기..."
37805,A034220,LG디스플레이,한국투자증권,유종우,-0.042994,2017,1,1,좋은 실적과 함께 로의 성공적인 전환이 필요한 때,"[(좋은, Adjective), (실적, Noun), (과, Josa), (함께, ..."
2154,A011780,금호석유,키움증권,박중선,-0.004597,2015,5,5,합성고무 수요 부진으로 실적 회복 더뎌,"[(합성, Noun), (고무, Noun), (수요, Noun), (부진, Noun..."
32171,A064420,케이피케미칼,신한금융투자,임지수,-0.014202,2010,5,5,분기 글로벌 자회사의 지분법 이익,"[(분기, Noun), (글로벌, Noun), (자회사, Noun), (의, Jos..."
...,...,...,...,...,...,...,...,...,...,...
15598,A000100,유한양행,KDB대우증권,김현태,-0.002495,2014,3,3,도입신약과 원료의약품이 실적 개선 견인,"[(도입, Noun), (신약, Noun), (과, Josa), (원료, Noun)..."
36744,A092200,디아이씨,신영증권,이재일,-0.010737,2016,11,11,분기 실적 혼조하지만 긍정적 요소의 장기 영향력이 우세,"[(분기, Noun), (실적, Noun), (혼, Noun), (조, Suffix..."
28076,A075180,새론오토모티브,하나금융투자,송선재,-0.036185,2017,3,3,중국 법인의 근본적인 성장 제고 방안이 필요,"[(중국, Noun), (법인, Noun), (의, Josa), (근본, Noun)..."
14823,A000830,삼성물산,토러스투자증권,박용희,-0.007227,2013,2,2,후기 년은 동사의 잠재력이 폭발하는 원년,"[(후기, Noun), (년, Noun), (은, Josa), (동사, Noun),..."
25708,A006280,녹십자,HMC투자증권,강양구,-0.000437,2017,2,2,모든 사업부 성장 중,"[(모든, Noun), (사업, Noun), (부, Noun), (성장, Noun)..."

In [24]:
# 명사만 추출하는 함수 
def extract_noun(word,pos): 
    Noun_words = []
    if pos =="Nouns":
        Noun_words.append(word)
    return Noun_words

ARCarm['noun_words']=ARCarm['nouns_pos'].apply(lambda word, pos: extract_noun(word,pos))

TypeError: <lambda>() missing 1 required positional argument: 'pos'

## toy

In [37]:
df = pd.DataFrame({"뉴스" :["오늘 날씨는 맑음입니다.","오늘 미세먼지는 나쁨입니다."]})
df

df['dict_okt']=df['뉴스'].apply(okt.pos)
df

# 명사만 추출하는 함수 
def extract_noun(word,pos): 
    Noun_words = []
    if pos =="Nouns":
        Noun_words.append(word)
    return Noun_words

# df['noun_words']=df['dict_okt'].apply(lambda word, pos: extract_noun(word,pos))

In [40]:
# 이거 한번 이용해보기 
df['dict_okt'][0][0][1]

'Noun'

In [41]:
# # 명사만 추출 
# Noun_words = []
# for word, pos in Okt_morphs:
#     if pos == 'Noun':
#         Noun_words.append(word)
# print(Noun_words)

# # 함수 참고 
# def d_vector(nouns):
#     d_=[]
#     for j in range(len(nouns)):
#         num_count = nouns.count(nouns[j])
#         d_.append(num_count)
#     return d_

# ARCarm['d']=ARCarm['nouns'].apply(lambda x: d_vector(x)) # d_vector 생성

# 불용어 정의 
stopwords = ['는','년','의','가','이','은','들','는','좀','잘','를','을','과','도','를','으로','자','에','와','한','하다','회','초', '이다', '일', '에서','다','월','일','있','하','것', '들', '그',
             '되', '수','하고','등','적','로','할','까지','하는','하','같','때','한','지','했다','하는','해','된다','된','있는','도록','뿐','고']

ARCarm['nouns_okt']=ARCarm['nouns_okt'].apply(lambda x: [item for item in x if item not in stopwords])

C:\Users\Public\Documents\ESTsoft\CreatorTemp/ipykernel_5536/1506486208.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ARCarm['nouns_okt']=ARCarm['title'].apply(okt.nouns) # 단어 토큰화
C:\Users\Public\Documents\ESTsoft\CreatorTemp/ipykernel_5536/1506486208.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ARCarm['nouns_okt']=ARCarm['nouns_okt'].apply(lambda x: [item for item in x if item not in stopwords])

In [42]:
ARCarm

,code,coname,house,analyst,carm,yy,mm,dd,title,nouns_okt
20880,A003550,LG,이베스트투자증권,양형모,0.014978,2015,10,10,그룹 변화의 바람으로 리레이팅,"[그룹, 변화, 바람, 리, 레이, 팅]"
19121,A005490,POSCO,교보증권,남광훈,-0.019651,2015,4,4,노이즈만 남았을 뿐 빅베쓰 는 끝났다,"[노이즈, 빅베쓰]"
31736,A064960,S&T모티브,토러스투자증권,채희근,0.002795,2009,7,7,하반기 정상 마진으로의 턴어라운드 전망,"[하반기, 정상, 마진, 턴, 라운드, 전망]"
7878,A095910,에스에너지,NH농협증권,최지환,-0.027368,2011,11,11,사업 확대로 수익성 개선 모색,"[사업, 확대, 수익, 개선, 모색]"
17159,A001800,오리온홀딩스,키움증권,우원성,-0.109759,2014,3,3,느려진 페이스 하지만 장기레이스,"[페이스, 장기, 레이스]"
...,...,...,...,...,...,...,...,...,...,...
23200,A012630,HDC,대신증권,이선일,0.026785,2016,10,10,갈수록 커지는 실적모멘텀 분기 실적,"[갈수록, 실적, 모멘텀, 분기, 실적]"
9928,A034120,SBS,키움증권,손윤경,-0.078372,2011,10,10,분기 실적 강력한 컨텐츠의 힘,"[분기, 실적, 컨텐츠, 힘]"
31757,A001120,LG상사,하이투자증권,민영상,0.027563,2009,11,11,분기이익 변동성보다 전체 수익성 레벨업에 주목,"[분기, 이익, 변동성, 전체, 수익, 레벨, 업, 주목]"
30549,A009540,한국조선해양,케이프투자증권,최진명,-0.023094,2018,6,6,분기가 실적의 바닥이 될 것으로 예상 실적 턴어라운드 임박,"[분기, 실적, 바닥, 예상, 실적, 턴, 라운드, 임박]"
14757,A010140,삼성중공업,키움증권,최원경,0.013538,2013,1,1,실적,[실적]

In [43]:
preprocessed_ARCarm=ARCarm

In [76]:
# preprocessed_ARCarm.to_csv('./preprocessed_ARCarm.csv',encoding='cp949')

### (1) - a. okt

In [ ]:
from konlpy.tag import Okt
okt = Okt() # Okt(Open Korea Text)

ARCarm['nouns_okt']=ARCarm['title'].apply(okt.nouns) 

# 불용어 정의 
stopwords = ['는','년','의','가','이','은','들','는','좀','잘','를','을','과','도','를','으로','자','에','와','한','하다','회','초', '이다', '일', '에서','다','월','일','있','하','것', '들', '그',
             '되', '수','하고','등','적','로','할','까지','하는','하','같','때','한','지','했다','하는','해','된다','된','있는','도록','뿐','고']

ARCarm['nouns_okt']=ARCarm['nouns_okt'].apply(lambda x: [item for item in x if item not in stopwords])
ARCarm

### (1) - b. twitter + spacing + okt

In [54]:
# !pip install customized_konlpy
# from ckonlpy.tag import Twitter
# twitter = Twitter()

# # Spacing 띄어쓰기
# !pip install git+https://github.com/haven-jeon/PyKoSpacing.git
# from pykospacing import Spacing
# spacing = Spacing()

# ARCarm['nouns_okt2']=ARCarm['title'].apply(twitter.morphs) # 형태소 by twitter

# # 불용어 정의 
# stopwords = ['는','년','의','가','이','은','들','는','좀','잘','를','을','과','도','를','으로','자','에','와','한','하다','회','초', '이다', '일', '에서','다','월','일','있','하','것', '들', '그',
#              '되', '수','하고','등','적','로','할','까지','하는','하','같','때','한','지','했다','하는','해','된다','된','있는','도록','뿐','고']
# # 불용어 제거 
# ARCarm['nouns_okt2']=ARCarm['nouns_okt2'].apply(lambda x: [item for item in x if item not in stopwords])
# ARCarm['nouns_okt2']=ARCarm['nouns_okt2'].apply(lambda x: "".join(x) )
# # 띄어쓰기 spacing 
# ARCarm['morphs']=ARCarm['nouns_okt2'].apply(lambda x: spacing(x) ) 
# # 형태소 토큰화 
# ARCarm['nouns_okt2']=ARCarm['nouns_okt2'].apply(okt.nouns)

Requirement already satisfied: customized_konlpy in c:\users\stat510\anaconda3\lib\site-packages (0.0.64)
Requirement already satisfied: Jpype1>=0.6.1 in c:\users\stat510\anaconda3\lib\site-packages (from customized_konlpy) (1.3.0)
Requirement already satisfied: konlpy>=0.4.4 in c:\users\stat510\anaconda3\lib\site-packages (from customized_konlpy) (0.6.0)
Requirement already satisfied: numpy>=1.6 in c:\users\stat510\anaconda3\lib\site-packages (from konlpy>=0.4.4->customized_konlpy) (1.19.5)
Requirement already satisfied: lxml>=4.1.0 in c:\users\stat510\anaconda3\lib\site-packages (from konlpy>=0.4.4->customized_konlpy) (4.6.3)

### (2) komoran

In [59]:
from konlpy.tag import Komoran
komoran=Komoran()  

# 단어 토큰화 
ARCarm['nouns_komoran']=ARCarm['title'].apply(komoran.nouns) 

# 불용어 정의 
stopwords = ['는','년','의','가','이','은','들','는','좀','잘','를','을','과','도','를','으로','자','에','와','한','하다','회','초', '이다', '일', '에서','다','월','일','있','하','것', '들', '그',
             '되', '수','하고','등','적','로','할','까지','하는','하','같','때','한','지','했다','하는','해','된다','된','있는','도록','뿐','고']

ARCarm['nouns_komoran']=ARCarm['nouns_komoran'].apply(lambda x: [item for item in x if item not in stopwords])
ARCarm

java.lang.NullPointerException: java.lang.NullPointerException

### (3) Hannanum

In [ ]:
from konlpy.tag import Hannanum
Hannanum=Hannanum()

# 단어 토큰화 
ARCarm['nouns_Hannanum']=ARCarm['title'].apply(Hannanum.nouns) # 단어 토큰화 

# 불용어 정의 
stopwords = ['는','년','의','가','이','은','들','는','좀','잘','를','을','과','도','를','으로','자','에','와','한','하다','회','초', '이다', '일', '에서','다','월','일','있','하','것', '들', '그',
             '되', '수','하고','등','적','로','할','까지','하는','하','같','때','한','지','했다','하는','해','된다','된','있는','도록','뿐','고']
# 불용어 제거 
ARCarm['nouns_Hannanum']=ARCarm['nouns_Hannanum'].apply(lambda x: [item for item in x if item not in stopwords])

ARCarm

### (4) Kkma

In [ ]:
from konlpy.tag import Kkma
Kkma=Kkma() 

# 단어 토큰화 
ARCarm['nouns_Kkma']=ARCarm['title'].apply(Kkma.nouns) # 단어 토큰화 

# 불용어 정의 
stopwords = ['는','년','의','가','이','은','들','는','좀','잘','를','을','과','도','를','으로','자','에','와','한','하다','회','초', '이다', '일', '에서','다','월','일','있','하','것', '들', '그',
             '되', '수','하고','등','적','로','할','까지','하는','하','같','때','한','지','했다','하는','해','된다','된','있는','도록','뿐','고']
# 불용어 제거 
ARCarm['nouns_Kkma']=ARCarm['nouns_Kkma'].apply(lambda x: [item for item in x if item not in stopwords])

ARCarm

### 열이름 변경

In [ ]:
# 선택하여 열 이름 변경하기
df.rename(columns={'nouns_okt':'nouns'})
df.rename(columns={'nouns_okt2':'nouns'})
df.rename(columns={'nouns_Hannanum':'nouns'})
df.rename(columns={'nouns_Kkma':'nouns'})

## 각 title별로 몇번의 단어가 등장했는지

In [185]:
def d_vector(nouns):
    d_=[]
    for j in range(len(nouns)):
        num_count = nouns.count(nouns[j])
        d_.append(num_count)
    return d_

ARCarm['d']=ARCarm['nouns'].apply(lambda x: d_vector(x)) # d_vector 생성

C:\Users\Public\Documents\ESTsoft\CreatorTemp/ipykernel_12380/762884296.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ARCarm['d']=ARCarm['nouns'].apply(lambda x: d_vector(x)) # d_vector 생성

In [186]:
ARCarm

,code,coname,house,analyst,carm,yy,mm,dd,title,nouns,d
39250,A039490,키움증권,유안타증권,원재웅,0.020847,2014,11,11,내년부터 자회사도 정상화 증권도 정상화,"[내년, 자회사, 정상화, 증권, 정상화]","[1, 1, 2, 1, 2]"
4044,A002550,KB손해보험,신영증권,이병건,0.107421,2009,9,9,저평가 이상을 논하기엔 너무 싸다 분석,"[평가, 이상, 논, 분석]","[1, 1, 1, 1]"
14776,A032640,LG유플러스,키움증권,안재민,0.027079,2013,3,3,의 실적 견인과 의 가입자 확보,"[의, 실적, 견인, 의, 가입자, 확보]","[2, 1, 1, 2, 1, 1]"
34072,A005380,현대차,HMC투자증권,이명훈,-0.026320,2013,2,2,년 이익 방어의 핵심은 중국,"[년, 이익, 방어, 핵심, 중국]","[1, 1, 1, 1, 1]"
8897,A000660,SK하이닉스,삼성증권,김도한,0.053394,2011,1,1,분기 점차 강조되는 의 중요성,"[분기, 점차, 강조, 의, 중요성]","[1, 1, 1, 1, 1]"
...,...,...,...,...,...,...,...,...,...,...,...
14606,A039130,하나투어,유진투자증권,이우승,0.089290,2013,1,1,큰 폭의 성장,"[폭, 성장]","[1, 1]"
9842,A004710,한솔테크닉스,키움증권,김병기,-0.021208,2011,3,3,태양광 모듈 매출 시작 주력사업 전환의 신호탄,"[태양광, 모듈, 매출, 시작, 주력, 사업, 전환, 신호탄]","[1, 1, 1, 1, 1, 1, 1, 1]"
5026,A006400,삼성SDI,KTB투자증권,민천홍,0.041951,2010,3,3,탐방보고,"[탐방, 보고]","[1, 1]"
33131,A086280,현대글로비스,유진투자증권,주익찬,0.040842,2011,5,5,전망 영업이익은 과 비슷할 전망,"[전망, 영업, 이익, 과, 전망]","[2, 1, 1, 1, 2]"
30664,A031980,피에스케이홀딩스,키움증권,한동희,0.109561,2018,5,5,리레이팅을 예상하는 이유,"[리레이팅, 예상, 이유]","[1, 1, 1]"

# toy

In [146]:
from konlpy.tag import Komoran
from konlpy.tag import Hannanum
from konlpy.tag import Kkma
komoran=Komoran()  
Hannanum=Hannanum()
Kkma=Kkma()

In [184]:

df = pd.DataFrame({"뉴스" :["오늘 날씨는 맑음입니다.","오늘 미세먼지는 나쁨입니다."]})
df

df['dict_okt']=df['뉴스'].apply(okt.nouns)
# df['dict_komoran']=df['뉴스'].apply(komoran.nouns)
# df['dict_Hannanum']=df['뉴스'].apply(Hannanum.nouns)
# df['dict_Kkma']=df['뉴스'].apply(Kkma.nouns)

df.head()

# ARCarm['nouns']=ARCarm['title'].apply(okt.nouns) # 단어 토큰화 

def d_vector(nouns):
    d_=[]
    for j in range(len(nouns)):
        num_count = nouns.count(nouns[j])
        d_.append(num_count)
    return d_


df['d']=df['dict_okt'].apply(lambda x: d_vector(x)) # d_vector 생성
df

                뉴스      dict_okt          d
0    오늘 날씨는 맑음입니다.  [오늘, 날씨, 맑음]  [1, 1, 1]
1  오늘 미세먼지는 나쁨입니다.    [오늘, 미세먼지]     [1, 1]

In [179]:
list=[]
# j = 0
# a = df['dict_okt'][0]
# num_count=a.count(a[j])
list.append(1)

# print(a)
# print(num_count)
# print(d_vector)

In [181]:
list.append(1)
list

[1, 1, 1]

In [116]:
def d_vector(nouns):
    d_=list()
    for j in range(len(nouns)):
        num_count = nouns.count(nouns[j])
        d_=d_.append(num_count)
    return d_


ARCarm['d']=ARCarm['nouns'].apply(lambda x: d_vector(x)) # d_vector 생성

[1]

In [119]:
ARCarm

,code,coname,house,analyst,carm,yy,mm,dd,title,nouns,d
39250,A039490,키움증권,유안타증권,원재웅,0.020847,2014,11,11,내년부터 자회사도 정상화 증권도 정상화,"[내년, 자회사, 정상화, 증권, 정상화]",None
4044,A002550,KB손해보험,신영증권,이병건,0.107421,2009,9,9,저평가 이상을 논하기엔 너무 싸다 분석,"[평가, 이상, 논, 분석]",None
14776,A032640,LG유플러스,키움증권,안재민,0.027079,2013,3,3,의 실적 견인과 의 가입자 확보,"[의, 실적, 견인, 의, 가입자, 확보]",None
34072,A005380,현대차,HMC투자증권,이명훈,-0.026320,2013,2,2,년 이익 방어의 핵심은 중국,"[년, 이익, 방어, 핵심, 중국]",None
8897,A000660,SK하이닉스,삼성증권,김도한,0.053394,2011,1,1,분기 점차 강조되는 의 중요성,"[분기, 점차, 강조, 의, 중요성]",None
...,...,...,...,...,...,...,...,...,...,...,...
14606,A039130,하나투어,유진투자증권,이우승,0.089290,2013,1,1,큰 폭의 성장,"[폭, 성장]",None
9842,A004710,한솔테크닉스,키움증권,김병기,-0.021208,2011,3,3,태양광 모듈 매출 시작 주력사업 전환의 신호탄,"[태양광, 모듈, 매출, 시작, 주력, 사업, 전환, 신호탄]",None
5026,A006400,삼성SDI,KTB투자증권,민천홍,0.041951,2010,3,3,탐방보고,"[탐방, 보고]",None
33131,A086280,현대글로비스,유진투자증권,주익찬,0.040842,2011,5,5,전망 영업이익은 과 비슷할 전망,"[전망, 영업, 이익, 과, 전망]",None
30664,A031980,피에스케이홀딩스,키움증권,한동희,0.109561,2018,5,5,리레이팅을 예상하는 이유,"[리레이팅, 예상, 이유]",None

In [77]:
d_vector

[1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 ...]

In [33]:
i = 0
d = ARCarm['nouns'].iloc[i] # i번재 해당되는 단어들 
print(len(d))
print(d)
j = d[j]
count = tf(j,d)
d_vector.append()

5
['내년', '자회사', '정상화', '증권', '정상화']

TypeError: list indices must be integers or slices, not str

In [ ]:
for i in range(len(preprocessed_ARCarm)):
    d = preprocessed_ARCarm['nouns'].iloc[i]
    for j in range(len(d)):
        t = j
        preprocessed_ARCarm['d']= tf(t,d)

## tf행렬

In [77]:
def tf(t, d):
  return d.count(t)

In [79]:
vocab = []
# vocab.append(text['morphs'][3])
# text['morphs'].iloc[1]
for i in range(len(preprocessed_ARCarm)): 
    vocb = vocab.append(preprocessed_ARCarm['nouns'].iloc[i])

In [ ]:
result = []

for i in range(len(preprocessed_ARCarm)):
    result.append([])
    d= preprocessed_ARCarm['nouns'].iloc[i] 
    for j in range(len(vocab)):
        t = vocab[j]
        result[-1].append(tf(t,d))

tf_ = pd.DataFrame(result, columns = vocab)

In [ ]:
pd.DataFrame(tf_.apply(lambda x: sum(x))).T